apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-cert-request
  namespace: istio-ingress
spec:
  secretName: unifi-cert-request
  duration: 2160h
  renewBefore: 48h
  privateKey:
    rotationPolicy: Always
  commonName: unifi.${DOMAIN_NAME}
  dnsNames:
    - unifi.${DOMAIN_NAME}
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
