name: Build Unifi Network Application Server image
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Unifi Network Application Server Image
      env:
        DOCKER_USER: ${{ vars.DOCKER_USERNAME }}
        IMAGE_NAME: unifi-network-server
        GIT_REF: ${{ github.ref_name }}
      run: |
        IMAGE_TAG="${GIT_REF#v}"
        echo "Pushing: $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG"
        docker build . -t "$DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG"
        docker push "$DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG"
        echo "Pushing: $DOCKER_USER/$IMAGE_NAME:latest"
        docker tag "$DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG" "$DOCKER_USER/$IMAGE_NAME:latest"
        docker push "$DOCKER_USER/$IMAGE_NAME:latest"
